name: Build NewCam
on:
  push:
    branches: [ chips-hmp ]
  pull_request:
    branches: [ chips-hmp ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setting initial vars
        run: |
           git config --global user.name "Omar Hamad"
           git config --global user.email "etahamad@icloud.com"
           git config --global color.ui false
      
      - name: Cloning dependencies
        run: |
           git clone --depth=1 https://github.com/sohamxda7/llvm-stable  clang
           git clone --depth=1 https://github.com/sohamxda7/llvm-stable -b gcc64 gcc
           git clone --depth=1 https://github.com/sohamxda7/llvm-stable -b gcc32 gcc32
           git clone --depth=1 https://github.com/etahamad/AnyKernel3 -b lavender AnyKernel
      
      - name: Picking NewCam commit
        run: |
           git fetch https://github.com/stormbreaker-project/kernel_xiaomi_lavender d676ba09bd1d48511f124ba35d575cc6590b5aab
           git cherry-pick FETCH_HEAD

      - name: Building
        run: bash .github/workflows/build.sh
        env:
          CAM: NewCam
          token: ${{ secrets.TELEGRAM_CI_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CI_CHANNEL_ID }}
